### ISSUE TITLE
[Feature Request] Implement custom/changeable home path

### ISSUE THREAD

**Issue by Foxxyne** [facundoolano/rpg-cli#100]
Hello there!
Am here to ask for the possibility of implementing a custom or a way to change the home path from "~" on the rpg-cli.
I work with longer file system paths now and would be nice to have a way to change it.

Thanks!

**Comment by facundoolano** [comment]
Hi. The game uses the [dirs crate](https://crates.io/crates/dirs) to determine the user home dir. According to [their doc](https://docs.rs/dirs/3.0.2/dirs/fn.home_dir.html) you may be able to point to a different home dir by setting the `$HOME` environment variable. Can you check if that suits your needs or, if not, provide more details of your use case?

**Comment by Foxxyne** [comment]
Setting the $HOME did work, it actually is an easy way to configure "~" to wherever you need. I just don't know if that will affect other things in the system.
As a workaround I think this works well, I can see how using $HOME is easier.

**Comment by facundoolano** [comment]
You can always define a wrapper function for the rpg command so it doesn't affect other uses of that variable, e.g.

```shell
rpg () {
    HOME=/my/home/override rpg-cli "$@"
}
```
