### ISSUE TITLE
Going to $HOME with --force flag doesn't reset character stats or apply ring/status effects

### ISSUE THREAD

**Issue by zoomiti** [facundoolano/rpg-cli#123]
These are the commands I type into the command line to try to go home to reset my characters HP but it never happens

```
[zoomiti@MastermindRogue ~]$ rpg-cli pwd
/home/zoomiti
[zoomiti@MastermindRogue ~]$ rpg-cli stat
    mage[1]@home
    hp:[xxxxx-----] 14/28
    mp:[xxx-------] 3/12
    xp:[xxxxxx----] 17/30
    att:3   mag:33   def:0   spd:11
    equip:{}
    item:{}
    46g
[zoomiti@MastermindRogue ~]$ rpg-cli cd ~
[zoomiti@MastermindRogue ~]$
```

For the record I am on 1.0.0
```
[zoomiti@MastermindRogue ~]$ rpg-cli -V
rpg-cli 1.0.0
```

**Comment by facundoolano** [comment]
Hi @zoomiti . What's your system and what's the value of the $HOME environment variable?

**Comment by zoomiti** [comment]
I double checked and it was /home/zoomiti

**Comment by facundoolano** [comment]
I see. What happens if you `rpg cd .. && rpg cd ~`? (this is: move out of home and then come back)

**Comment by zoomiti** [comment]
That works actually, I suspect it has to do with the way I set up my bashrc. Because I force the cd (I don't like having to traverse a directory at a time/have to change the cd path due to the new context.) I think rpg cd -f ~ doesn't reset your character the same way it doesn't start battles.

``` 
$ cat ~/.bashrc
...
cd () {
    builtin cd "$@"
    command ls --color=auto
    rpg-cli cd -f .
    rpg-cli battle
}
...
```

**Comment by zoomiti** [comment]
```
$ rpg-cli cd -f ~
$
```
It seems like I am right, not sure if this is intended or if I should just circumvent it with a check for going home so that I don't force cd'ing into the home directory...

**Comment by zoomiti** [comment]
I figured out a work around that seems to work for now in case this is intended behavior.

```
cd () {
     builtin cd "$@"
     if [[ $PWD== ~ ]] ; then
         rpg-cli cd ~
     else
         rpg-cli cd -f .
         rpg-cli battle
     fi
 }
```

**Comment by facundoolano** [comment]
Right, that's is the consequence `--force` option works: it just overrides the current location/directory, but doesn't apply the side-effects of visiting that directory. This made sense back when I first implemented it, but I'm now considering that the most consistent behavior would be to actually apply side effects (both resetting of char stats in home and applying status/ring effects such as poison damage).
