### ISSUE TITLE
please run `reset --hard` to restart.

### ISSUE THREAD

**Issue by e3e0261f** [facundoolano/rpg-cli#131]
**Invalid game data file. If it was generated with a previous version please run `reset --hard` to restart.**

```

~ $ rpg-cli pwd
/home/～/.config/glib-2.0
~ $ rpg-cli cd ~
~ $ rpg-cli pwd
/home/～/.config
~ $ rpg-cli cd ~
~ $ rpg-cli cd ~
~ $ rpg-cli cd ~
~ $ rpg-cli cd ~
~ $ rpg-cli cd ~
     rat[5][xxxx][----]@~/.config
     rat[5][----] -201hp
 warrior[21][xxxx] +0xp
 warrior[21][xxxx][----][x---]@~/.config
~ $ rpg-cli cd ~
    wolf[5][xxxx][----]@~/.dbus
    wolf[5][----] -264hp
 warrior[21][xxxx] +0xp
 warrior[21][xxxx][----][x---]@~/.dbus
~ $ rpg-cli cd ~
~ $ rpg-cli cd ~
~ $ rpg-cli cd ~
~ $ rpg-cli cd ~
~ $ rpg-cli cd ~
Invalid game data file. If it was generated with a previous version please run `reset --hard` to restart.
~ $ rpg-cli cd ~
Invalid game data file. If it was generated with a previous version please run `reset --hard` to restart.
~ $ rpg-cli cd ~
Invalid game data file. If it was generated with a previous version please run `reset --hard` to restart.
~ $ rpg-cli cd ~
Invalid game data file. If it was generated with a previous version please run `reset --hard` to restart.
~ $ rpg-cli cd ~
Invalid game data file. If it was generated with a previous version please run `reset --hard` to restart.
~ $ rpg-cli cd ~
Invalid game data file. If it was generated with a previous version please run `reset --hard` to restart.
~ $

```

**Comment by facundoolano** [comment]
Hi! What rpg-cli version are you running? Can you paste here the contents of ~/.rpg/data ?

**Comment by e3e0261f** [comment]
*  games-rpg/rpg-cli
      Latest version available: 1.0.0
      Latest version installed: 1.0.0
      Size of files: 9,720 KiB
      Homepage:      https://github.com/facundoolano/rpg-cli
      Description:   Terminal game, your filesystem as a dungeon
      License:       Apache-2.0 MIT

DATA 
`{"player":{"class":{"name":"mage","hp":[30,6],"mp":[10,4],"strength":[10,3],"speed":[10,2],"category":"player","inflicts":null},"level":53,"xp":1827,"max_hp":319,"current_hp":319,"max_mp":249,"current_mp":177,"strength":147,"speed":117,"sword":["sword",100],"shield":["shield",15],"left_ring":null,"right_ring":null,"status_effect":null},"location":{"path":"/home/lee/down"},"gold":417929,"inventory":{"mp-stone":[{"type":"Magic"},{"type":"Magic"},{"type":"Magic"}],"potion":[{"type":"Potion","level":1},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":1},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":1},{"type":"Potion","level":1},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":1},{"type":"Potion","level":1},{"type":"Potion","level":1},{"type":"Potion","level":1},{"type":"Potion","level":1},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":1},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":1},{"type":"Potion","level":1},{"type":"Potion","level":1},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":10},{"type":"Potion","level":1},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5},{"type":"Potion","level":5}],"ether":[{"type":"Ether","level":1},{"type":"Ether","level":10},{"type":"Ether","level":5},{"type":"Ether","level":10},{"type":"Ether","level":10},{"type":"Ether","level":10},{"type":"Ether","level":1},{"type":"Ether","level":5},{"type":"Ether","level":5},{"type":"Ether","level":10},{"type":"Ether","level":10},{"type":"Ether","level":10},{"type":"Ether","level":5},{"type":"Ether","level":5},{"type":"Ether","level":5},{"type":"Ether","level":5},{"type":"Ether","level":10},{"type":"Ether","level":10},{"type":"Ether","level":10},{"type":"Ether","level":10},{"type":"Ether","level":1},{"type":"Ether","level":5},{"type":"Ether","level":10},{"type":"Ether","level":10},{"type":"Ether","level":5},{"type":"Ether","level":5},{"type":"Ether","level":5},{"type":"Ether","level":5},{"type":"Ether","level":5},{"type":"Ether","level":5},{"type":"Ether","level":5},{"type":"Ether","level":5},{"type":"Ether","level":10},{"type":"Ether","level":10},{"type":"Ether","level":10},{"type":"Ether","level":10},{"type":"Ether","level":10},{"type":"Ether","level":1},{"type":"Ether","level":5},{"type":"Ether","level":5},{"type":"Ether","level":5}],"escape":[{"type":"Escape"},{"type":"Escape"},{"type":"Escape"},{"type":"Escape"},{"type":"Escape"},{"type":"Escape"},{"type":"Escape"},{"type":"Escape"},{"type":"Escape"},{"type":"Escape"},{"type":"Escape"},{"type":"Escape"},{"type":"Escape"},{"type":"Escape"},{"type":"Escape"},{"type":"Escape"},{"type":"Escape"}],"remedy":[{"type":"Remedy"},{"type":"Remedy"},{"type":"Remedy"},{"type":"Remedy"},{"type":"Remedy"},{"type":"Remedy"},{"type":"Remedy"},{"type":"Remedy"},{"type":"Remedy"},{"type":"Remedy"},{"type":"Remedy"},{"type":"Remedy"},{"type":"Remedy"},{"type":"Remedy"},{"type":"Remedy"},{"type":"Remedy"},{"type":"Remedy"}],"hp-stone":[{"type":"Health"},{"type":"Health"},{"type":"Health"},{"type":"Health"},{"type":"Health"},{"type":"Health"},{"type":"Health"},{"type":"Health"},{"type":"Health"},{"type":"Health"},{"type":"Health"}],"lvl-stone":[{"type":"Level"}]},"inspected":[{"path":"/home/lee/.local"},{"path":"/home/lee/.fltk"},{"path":"/home/lee/node_modules"},{"path":"/home/lee/dungeon"},{"path":"/home/lee/.rpg"},{"path":"/home/lee"},{"path":"/home/lee/Sync"},{"path":"/home/lee/.msf4"},{"path":"/home/lee/.steam"},{"path":"/home/lee/.dbus"},{"path":"/home/lee/note"},{"path":"/home/lee/Desktop"},{"path":"/home/lee/video"},{"path":"/home/lee/.TeXmacs"},{"path":"/home/lee/.step"},{"path":"/home/lee/Games"},{"path":"/home/lee/.npm"},{"path":"/home/lee/.oh-my-zsh"},{"path":"/home/lee/.pki"},{"path":"/home/lee/down"},{"path":"/home/lee/.config"},{"path":"/home/lee/.ssh"},{"path":"/home/lee/music"},{"path":"/home/lee/News"},{"path":"/home/lee/.emacs.d"},{"path":"/home/lee/images"},{"path":"/home/lee/.advance"},{"path":"/home/lee/.mozilla"},{"path":"/home/lee/.audacity-data"},{"path":"/home/lee/.wine"},{"path":"/home/lee/.schism"},{"path":"/home/lee/.w3m"},{"path":"/home/lee/文档"},{"path":"/home/lee/.log"},{"path":"/home/lee/.cache"},{"path":"/home/lee/Mail"},{"path":"/home/lee/.mplayer"},{"path":"/home/lee/.lincity"}],"tombstones":{},"ring_pool":["Fire","Evade","Counter","Attack","RegenMP","Speed","Magic","Chest","Deffense","Ruling","Double","Gold","MP","RegenHP","Protect","HP","Revive","Void","Poison"],"quests":{"quests":[["Completed",100,{"type":"WinBattle"}],["Completed",100,{"type":"BuySword"}],["Completed",100,{"type":"UsePotion"}],["Completed",100,{"type":"ReachLevel","target":2}],["Completed",200,{"type":"FindChest"}],["Completed",500,{"type":"ReachLevel","target":5}],["Completed",1000,{"type":"BeatEnemyClass","to_beat":[],"total":5,"description":"beat all common creatures"}],["Completed",200,{"type":"VisitTomb"}],["Unlocked",300,{"type":"EquipRing"}],["Completed",1000,{"type":"ReachLevel","target":10}],["Completed",5000,{"type":"BeatEnemyClass","to_beat":[],"total":8,"description":"beat all rare creatures"}],["Unlocked",1000,{"type":"BeatEnemyDistance","distance":10}],["Unlocked",10000,{"type":"BeatEnemyClass","to_beat":["balrog","basilisk","minotaur","chimera","phoenix"],"total":5,"description":"beat all legendary creatures"}],["Completed",10000,{"type":"ReachLevel","target":50}],["Completed",5000,{"type":"RaiseClassLevels","remaining":0,"class_name":"warrior"}],["Completed",5000,{"type":"RaiseClassLevels","remaining":-1,"class_name":"mage"}],["Unlocked",5000,{"type":"RaiseClassLevels","remaining":5,"class_name":"thief"}],["Unlocked",30000,{"type":"FindAllRings","to_find":["Gold","Revive","Void","Diamond","Fire","Deffense","HP","Magic","Counter","Chest","MP","Attack","Ruling","RegenHP","RegenMP","Evade","Poison","Speed","Protect","Double"]}],["Completed",20000,{"type":"BeatEnemyClass","to_beat":[],"total":1,"description":"beat your own shadow"}],["Completed",20000,{"type":"BeatEnemyClass","to_beat":[],"total":1,"description":"beat the dev"}],["Unlocked",100000,{"type":"ReachLevel","target":100}],["Unlocked",1000000,{"type":"BeatEnemyClass","to_beat":["gorthaur"],"total":1,"description":"carry the ruling ring to the deeps to meet its maker"}]]}}]}} `

**Comment by facundoolano** [comment]
hey @e3e0261f the JSON you pasted looks invalid (it has some extra trailing `]}}` at the end. Is there a chance that either you had a typo when pasting or edited the data file by mistake? 

The error should go away by removing those extra characters but I don't get how you would arrive to such malformed json through the rpg-cli program. Do you arrive to the same error when starting a new game?

**Comment by e3e0261f** [comment]
script
`#!/bin/bash

load-level(){
    le_1=$(rpg-cli |sed -n '1p'|sed 's/^.*\[//'|sed 's/.@.*$//')
    xp_1=$(rpg-cli |sed -n '4p'|sed 's/^.*\].//'|sed 's/\/.*$//')
    }
load-level
viewdata(){
    rpg-cli pwd
    echo $le_2
    echo $le_1
    echo $xp_1
    echo $xp_2
}
viewdata

backup(){
    cp ~/.rpg/data ~/.rpg/data.old
}
backup

sleep_1(){
sleep 1
}

function get_char()
{
    SAVEDSTTY=`stty -g`
    stty -echo
    stty cbreak
    dd if=/dev/tty bs=1 count=1 2> /dev/null
    stty -raw
    stty echo
    stty $SAVEDSTTY
}

function pause()
{
    enable_pause=1
    if [ "x$1" != "x" ]; then
	echo $1
    fi
    if [ $enable_pause -eq 1 ]; then
	echo "PAUSE!"
	char=`get_char`
    fi
}

auto-recover(){
    enable_recover=1;
    if [ -n "$(echo sed "1 s@level@levellll@" .rpg/data| sed "1 s@xp@xppppp@"|sed "1 s@.*levellll..@@"|sed \
"1 s@..xppppp.*@@" )" ];then
	echo ""
    else
        echo $le_1| sed -n "/^[0-9]\+$/p"
	echo "DATA ERR，"
	sleep_1
	if [ $enable_pause -eq 1 ] &> /dev/null; then
	pause
	fi
        viewdata
	cp /tmp/data.old2 ~/.rpg/data && echo "recover DATA-2 DONE"
#       exit 1
    fi
    if [ $le_2 -lt 10 ] &> /dev/null; then
	echo "DIE，LEVE$le_2.."
	cp /tmp/data.old2 ~/.rpg/data && echo "RISE DONE"
	rpg-cli pwd >> /tmp/2.line
	sleep_1
    fi
}

ui=1
du -d "$1"  > /tmp/2.line
sed "s/^.*\s//" /tmp/2.line -i
sort /tmp/2.line | uniq > /tmp/1.line
home() {
    rpg-cli cd "~" && xp_2=$(rpg-cli |sed -n '4p'|sed 's/^.*\].//'|sed 's/\/.*$//')
}
uplevel_backup(){
    le_2=$(rpg-cli |sed -n '1p'|sed 's/^.*\[//'|sed 's/.@.*$//')
    xp_2=$(rpg-cli |sed -n '4p'|sed 's/^.*\].//'|sed 's/\/.*$//')
    if [ "$le_2" -gt "$le_1" ] &> /dev/null;
    then
        cp ~/.rpg/data /tmp/data.old2
	echo "Level UP $le_1 -> $le_2"
	le_1=$[le_2]
	load-level
	sleep_1
    fi
    if [ "$xp_2" -gt "$xp_1" ] &> /dev/null;
    then
        cp ~/.rpg/data /tmp/data.old2
	echo "Experience UP $xp_1 --> $xp_2"
	xp_1=$[xp_2]
	load-level
	sleep_1
    fi
}
go() {
z    for line in $(cat /tmp/1.line)
    do
        auto-recover
        uplevel_backup
        rpg-cli cd "${line}"
        rpg-cli battle
        rpg-cli ls
        rpg-cli pwd
        ui=$[ui+1]
#        echo "$ui"
    done
}
while ((i <= $2))
do
    ((i++))
    go
    home
#    echo "----------------------------------$i"
done
rpg-cli buy sword shield potion ether remedy escape
rpg-cli use str-stone &> /dev/null
rpg-cli use spd-stone &> /dev/null
rpg-cli use def-stone &> /dev/null
rpg-cli use hp-stone &> /dev/null
rpg-cli use mp-stone &> /dev/null
rpg-cli stat
viewdata
`

**Comment by facundoolano** [comment]
I noticed there's a unicode dir name in your user data `"/home/lee/文档"`, maybe that's breaking your script somehow?

**Comment by facundoolano** [comment]
@e3e0261f could you figure out what the problem was?
