### ISSUE TITLE
Not recognicing $HOME when used with cd -f

### ISSUE THREAD

**Issue by mowgli** [facundoolano/rpg-cli#140]
When using the variant with cd -f, rpg does not recognice $HOME so no healing will be done anymore.

**Comment by facundoolano** [comment]
What version are you trying this on? it should have been fixed in [1.0.1](https://github.com/facundoolano/rpg-cli/blob/main/CHANGELOG.md#fixed)

**Comment by mowgli** [comment]
Ah, yes. I use the version from Gentoo, which is 1.0.0
