### ISSUE TITLE
disable shop items

### ISSUE THREAD

**Issue by octoshrimpy** [facundoolano/rpg-cli#144]
![image](https://github.com/facundoolano/rpg-cli/assets/7097172/8e2e6830-2b84-420e-a57a-a12d0ed2648a)

as per screenshot, I cannot upgrade sword, but it still shows as a viable purchase. maybe gray-out the name and replace the pric with "owned" ?

**Comment by facundoolano** [comment]
why do you say it still shows as a valid purchase? it's not on the list in the second command.

**Comment by octoshrimpy** [comment]
you're right! tired eyes completely glazed over!
