### ISSUE TITLE
Panics with `.` as argument in Windows

### ISSUE THREAD

**Issue by SirWindfield** [facundoolano/rpg-cli#17]
```console
$ rpg-cli.exe .
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\location.rs:43:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by facundoolano** [comment]
I had similar reports of the program failing in windows when pointing to `~`.

Does this happen on PowerShell? with the `$HOME` env set.

(I'm not familiar with current shell situation in Windows, I didn't expect this to be usable in that OS but maybe it can).

**Comment by Coding-Badly** [comment]
``` rust
    pub fn go_to(&mut self, dest: &Self) {
        if !dest.path.starts_with(&self.path) {
            println!("dest.path = {:?}", dest.path);
            println!("self.path = {:?}", self.path);
            self.path = self.path.parent().unwrap().to_path_buf();
```

The output from `cargo run -- .`...

``` text
dest.path = "\\\\?\\C:\\Users\\brian\\Documents\\rpg-cli"
self.path = "C:\\Users\\brian"

     rat[2][xxxx]@C:\Users
...
```

A caveat with Windows.  Some Rust functions convert a path to UNC.  Ideally, paths meant to be compared should be first converted to UNC.  (canonicalize)[https://doc.rust-lang.org/std/fs/fn.canonicalize.html] will probably help.

**Comment by facundoolano** [comment]
We're actually [already using canonicalize](https://github.com/facundoolano/rpg-cli/blob/9b01b7d49ad3bcc70cea6a12c9762ab351d0de4a/src/location.rs#L22), and according to [this](https://github.com/rust-lang/rust/issues/42869) perhaps that's precisely where the UNC issue originates.

**Comment by facundoolano** [comment]
@SirWindfield, @Coding-Badly or anyone else interested in running this on windows, it would be useful if you can give it a try with the latest code from main.

It seemed to be fixed in the travis build on Windows but it would be better to get confirmation.

**Comment by SirWindfield** [comment]
I'll try later on :)
