### ISSUE TITLE
Shell prompt plugin

### ISSUE THREAD

**Issue by samoylovfp** [facundoolano/rpg-cli#19]
I'd love to have a switch for a "prompt" mode, so I can go around my business in terminal as usual while the action happens in the background, without printing lines of events
and just glancing occasionally at my shell prompt to see if I need to return to town to heal or buy more potions.

The output for actions can be redirected to /dev/null in the shell plugin itself, so no changes necessary, but adding a compact single-line output of current status, like hp percentage and a number of potions will really help make this.

I can do the actual implementation if the change is welcome.

**Comment by facundoolano** [comment]
This sounds like a cool idea. Do you think the rust side could be accommodated by having verbosity levels for the program? Or do you have something else in mind?

**Comment by facundoolano** [comment]
Well on second thought I guess it would be much easier to just have a separate arg `rpg --prompt` much like we already have `rpg --pwd`

**Comment by facundoolano** [comment]
This should now be available with the `rpg stat --plain` command. Let me know if it's not useful and feel free to send a PR with an example use for the [shell docs](https://github.com/facundoolano/rpg-cli/tree/main/shell).
