### ISSUE TITLE
Alternate installation method

### ISSUE THREAD

**Issue by spenserblack** [facundoolano/rpg-cli#20]
If you clone this repo and run `cargo install --path path/to/rpg-cli`, then the binary will be installed to `~/.cargo/bin`, and you can skip the step of moving the binary from `path/to/rpg-cli/target` to somewhere defined in `$PATH`.

You can also use `cargo install --git <URL>` to avoid manually cloning this repo.

**Comment by facundoolano** [comment]
Thanks, I'll incorporate this to the README.

**Comment by MattesWhite** [comment]
For me `cargo` looked by default for the branch `master` so the correct command was

`> cargo install --git https://github.com/facundoolano/rpg-cli --branch main`

**Comment by spenserblack** [comment]
Thanks @MattesWhite, I didn't realize that `--git` defaulted to `master`.

**Comment by MattesWhite** [comment]
I wondered why `cargo` did not already search for a `main` branch if `master` is not available. Turns out this was [issued a number of times](https://github.com/rust-lang/cargo/issues/3517) already. Following the discussion and PRs this should be solved within the next view releases of Rust.
