### ISSUE TITLE
Overflow

### ISSUE THREAD

**Issue by samoylovfp** [facundoolano/rpg-cli#21]
After using this for awhile I noticed this

![image](https://user-images.githubusercontent.com/17025459/119663265-e12aef00-be3a-11eb-9144-077c981f5198.png)

I was able to buy sword and shield of 175 level which is cool, but fights not happen pretty slowly

**Comment by facundoolano** [comment]
I'm exploring some fixes for this [here](https://github.com/facundoolano/rpg-cli/issues/21) in case someone wants to try it up and see how it plays.

**Comment by facundoolano** [comment]
@vito-laurenza-zocdoc I think that's a known issue with [cargo install](https://github.com/rust-lang/cargo/issues/2082).

Can you try again passing the `--force` flag to cargo install?

**Comment by vito-laurenza-zocdoc** [comment]
I tried with `--force`. I see a new timestamp on the file in `~/.cargo/bin/rpg-cli`. I can still reproduce the overflow.

```
$ rpg

    hero[165]@home
    hp:[xxxxxxxxxx] -1899234251/-1899234251
    xp:[x---------] 6142/63583
    att:-1854956476   def:4340737   spd:1113458
    equip:{sword[75],shield[75]}
    item:{}
    2078088g
```

**Comment by facundoolano** [comment]
ok, can you try running `rpg --reset` ? It's likely that you are running with the hero with overflowed stats from the previous version.

**Comment by vito-laurenza-zocdoc** [comment]
> ok, can you try running `rpg --reset` ? It's likely that you are running with the hero with overflowed stats from the previous version.

I meant to mention that I did `--reset` before grinding levels again.

**Comment by vito-laurenza-zocdoc** [comment]
> > ok, can you try running `rpg --reset` ? It's likely that you are running with the hero with overflowed stats from the previous version.
> 
> I meant to mention that I did `--reset` before grinding levels again.

I think I had `$RPG_CLI` pointing to a different binary. I'm trying again.
