### ISSUE TITLE
overflow

### ISSUE THREAD

**Issue by daef** [facundoolano/rpg-cli#22]
after leveling up a bit via

    for f in `seq 1000` ; do clear ; rpg /tmp ;clear; rpg ~ ; done ; clear ; rpg

I seem to have broken the stats:

    hero[160]@/home
    hp:[xxxxxxxxxx] -2085599079/-2085599079
    xp:[xxxxxxx---] 40302/60715
    att:-1989316420   def:6   spd:697466
    equip:{sword[1],shield[1]}
    item:{escapex15}
    5947886g

fights are pretty boring now, since they take forever

**Comment by facundoolano** [comment]
Thanks for reporting. I'm closing this one as duplicate of #21
