### ISSUE TITLE
Would be cool to have it in homebrew

### ISSUE THREAD

**Issue by phil-r** [facundoolano/rpg-cli#24]
it will make installation really easy on macOS

**Comment by facundoolano** [comment]
I agree, although this is not high on my priority list for now. I would appreciate if someone else does it, though (I'm not familiar with publishing to brew myself).

**Comment by DNA** [comment]
I've created one! 😄 
https://github.com/Homebrew/homebrew-core/pull/79379

Let's hope it's all okay and gets merged 🤞🏻

**Comment by DNA** [comment]
Aaaaand done! 🥳

I've also created a PR with a small update on the `README` about the brew install

**Comment by facundoolano** [comment]
Awesome, thanks!
