### ISSUE TITLE
Initiate a battle when running other file and dir commands

### ISSUE THREAD

**Issue by silky** [facundoolano/rpg-cli#25]
this is awesome; i love this project

i have long dreamed that something like this would exist!

it would be really cool to have a feature where you can start a battle that, if you win, results in the file being deleted!

**Comment by facundoolano** [comment]
I like this idea, it would work as a replacement for `rm` much like the default works as a replacement for `cd`. I'll think about this, thank you!

**Comment by facundoolano** [comment]
And if you ask to delete a dir it walks it recursively and you have a battle per file to be deleted

**Comment by facundoolano** [comment]
My current thinking on this one is that the same concept should apply to other file-modifying commands, not just rm: rmdir, mkdir, mv, cp, touch. If you attempt one of those commands a battle is initiated (perhaps not always but a % of the times); if you win, the command is executed as usual, if you lose, it doesn't (and the hero dies, of course).

Obviously attempting to reimplement all those commands (with their flags and variants) would be crazy, so what we should do instead is to have a generic command (`rpg-cli --alias` perhaps) that can be put in front of those in shell functions or aliases to achieve this "battle and proceed on win" behavior.

**Comment by 4censord** [comment]
`rpg-cli --alias` could be implemented via return codes.
Then we dont need do do anything with the actual command.

So we return 0 if:
* No monster is found
* The monster was bribed
* The hero wins

And we return not 0 if
* The Hero ran away
* The Hero died

## Examples
Bash:
```bash 
rpg-cli --alias && your-command --your-option
```
Fish
```fish
rpg-cli --alias ; and yourcommand --your-option
```

**Comment by facundoolano** [comment]
This should be possible with the new additions, documented in the [shell readme](https://github.com/facundoolano/rpg-cli/tree/main/shell#aliasing-other-commands)
