### ISSUE TITLE
Check in Cargo.lock

### ISSUE THREAD

**Issue by legendofmiracles** [facundoolano/rpg-cli#26]
This helps with reproducibility, and is also the recommended way for rust programs. 
The `.gitignore` says it ignores it, because this program is a library, which just isn't true.

It would also stop distro maintainers from having to patch in the Cargo.lock, as seen here: https://github.com/NixOS/nixpkgs/pull/124539/files

Thanks!

**Comment by facundoolano** [comment]
@legendofmiracles Thanks for reporting. 

When it's available, I would appreciate if you send a PR with instructions to install with nix [in the README](https://github.com/facundoolano/rpg-cli#setup).
