### ISSUE TITLE
macOS binary is unsigned, requiring Sec&Privacy adjustment

### ISSUE THREAD

**Issue by colindean** [facundoolano/rpg-cli#27]
I downloaded the binary and ran it on macOS 10.15.7. I got a security warning. I was able to open the Security & Privacy prefpane and allow it to run. The next time I ran it, I got the security warning again, but I was able to proceed.

**Comment by facundoolano** [comment]
Note that you can get around this without the sec&privacy change by opening the dir where binary is with Finder, right clicking the binary and clicking Open. If you allow permissions there you'll be able to run in the shell next time without problems. I could add a note for that in the README. 

I'm not familiar with the Apple signing process to prevent this altogether, I could look into it if it's not too onerous.

**Comment by facundoolano** [comment]
Added a nothe to the README about this.

**Comment by DNA** [comment]
Haven't done it yet, but it seems like a good tutorial: https://www.kencochrane.com/2020/08/01/build-and-sign-golang-binaries-for-macos-with-github-actions/

It feels like a lot of steps to setup, but can be automated easily :)

**Comment by facundoolano** [comment]
Closing this, as it's referred in the README already.
