### ISSUE TITLE
`rpg -` should take you to your last directory

### ISSUE THREAD

**Issue by jonathanmorley** [facundoolano/rpg-cli#31]
As well as being more usable as a cd replacement, this would allow users to more easily try to return to pick up their loot if they die.

**Comment by jonathanmorley** [comment]
There is an OLDPWD env var (at least on my system) that appears to help with this functionality

**Comment by facundoolano** [comment]
Right, we were discussing that in #30. I'm also considering rearranging the args such that `rpg` without arguments takes you home rather than prints the status (we could have something like `rpg --status` for that maybe?). Opinions are welcome.

**Comment by na-g** [comment]
@facundoolano I would definitely appreciate the ability to use this as a an alias to cd, and a naked `cd` is something I do all the time. Even having a flag like `rpg --cd ...` to make it behave exactly like cd (or in fact simply call `cd`) with the remainder of the CLI parameters would make it possible to construct such an alias.

**Comment by facundoolano** [comment]
At the moment I'm considering something like this:

* `rpg` defaults to a `cd` alias, including `-` and default to home as discussed here
* `--pwd` prints current location, as it does already
* `-s, --stat` print the current hero status
* `--rm` would remove files as discussed in #25 
* `-b, --buy` would replace the current shop command
* `-u, --use` would replace the current inventory command. Listing inventory contents seems kind of redundant with the general status.
