### ISSUE TITLE
Would be cool to have 'shell mod' + more stats + more interaction

### ISSUE THREAD

**Issue by Casul51** [facundoolano/rpg-cli#37]
**About 'shell mode'** - just execute some aliases like
```
*start another shell session*
go/cd  =  rpg-cli <arg>
shop =  rpg-cli -s
etc..
*exit from shell session for removing aliases and not breaking user's aliases*
```
good idea to make config where user set commands.
So, basicly it makes in script.

**About stats** - basicly i mean stats for stats check

**About more interactions** - basicly this #25 but let's say we want steal it instead and there comes hero's stats and stats check. User can chose way how to remove file - throw fight/steal, like that.
There is other actions:
```
edit txt = *speach check* (fail - refuse to edit file)
$ls = *perception check* (fail - don't show some files)
```

**Comment by facundoolano** [comment]
Thanks for the suggestions.
* The shell mode seems a bit out of scope, I think anyone can basically achieve this by writing a bash file (like those hinted in the README) and sourcing it whenever they feel like overriding the defaults with the rpg aliases. It sounds like what/how to alias is mostly a matter of personal preference so I hesitate to try to guess, but certainly if anyone has interesting examples or concrete suggestions in this area we can document them or potentially add support.
* I didn't get what you meant by the stats
* I'm considering more interactions and gathering feedback I got in reddit and elsewhere to come up with specific ideas that aren't too dependent on OS or presence of specific dir/files

I'm closing this issue as it's not actionable, but feel free to give more suggestions.
